#ENC[AES256_GCM,data:/BGx/WhtUIjC7oiv1k9VhMl5mp2+49wEfTHmuVYd4UdNAX0Lr9HT+Fisnhai9XINfRv8zb1tmJTTCw==,iv:t+0++AsUMG+uzHyZ/puqAVKZGVdAQrSNrLG9KUDWLsY=,tag:Z67CyBNA+y7id2pMj96+FA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: kube-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: argocd,base-system,applications,longhorn
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
data:
  users: ENC[AES256_GCM,data:/THDt8ZxQLo/31kfOfYinbhX0LtA8AJrTq/bdXI0wrrxxXh8wmvbAcU6rVYh+hBy1P9tsleTGqvwnaC55Q==,iv:zsPV49q8s60CbK7WIjBwHxXFOwu9wlNNKUwSZqWqywQ=,tag:gWMzvxiyjgA0SkGmGoEXjA==,type:str]
sops:
  age:
    - recipient: age1wk2gy8cquajzw70pzt9jlg0az96yzg5mzagj82m4098p59zju4qq3kyc6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c1czai8xNFJFRFNaaExr
        d2VBOWhOLzNpdHdYTFZlNXFjeVBFeUo4MkhvClpyY1c3SWhuTEVTaGQycDdWMzhh
        a3RtZVBWUVJTWklQbXRIalUvVUJob2cKLS0tIHVvUjlwVk0ybjhmYVZ0WlhjUTZM
        QklTYmJvYUlDUDVubitjeXpoU2MySVkKACZjOBMpaj82Fg1hTwrMwhIX7AvVCKh9
        Z19yQxf0seE8NcjCquuu3CCdX+o0tbW8AGaMbKVeRWP58c62JI0JFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T05:08:20Z"
  mac: ENC[AES256_GCM,data:gAsmUKRxuC3wQCkGORaO/ZOLupB4h8VzakaQlU3apS7BMve5jeX71nS/41xNeWktgl73CUF1EduY2ayEyEllkc5clQl2eHyHjd7GGXC0CSVmu3hgTFaa8tUkzjmnJllFMXqN8uDQYvkXPFReku+GB6GoYTpfPWN3wpZgCbUHb7g=,iv:DL4Kq12OZ82w78m+KCBFchczN6PT3N1guP6jcSWzSEU=,tag:VAzyuMuXeGpSqmya5GHzZA==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.10.2
