apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: kaspa-dnsseeder
  namespace: kaspa
spec:
  entryPoints:
    - dns
  routes:
    - services:
        - name: kaspa-dnsseeder
          port: 5354
