resources:
  - namespace.yaml
  - ./app.yaml
  # Kaspa Nodes
  - ./node/mainnet/app.yaml
  - ./node/next/app.yaml
  - ./node/tn12reset/app.yaml

  # Indexers
  - ./indexer/mainnet/app.yaml
  - ./indexer/next/app.yaml
  # Explorers
  - ./explorer/next/app.yaml
  # DNS Seeder
  - ./dnsseeder/next/app.yaml
