resources:
  - namespace.yaml
  - ./app.yaml
  # Kaspa Nodes
  - ./node/mainnet/app.yaml
  - ./node/testnet/app.yaml
  - ./node/next/app.yaml
  # Indexers
  - ./indexer/mainnet/app.yaml
  - ./indexer/testnet/app.yaml
  - ./indexer/next/app.yaml
