apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kaspad
  namespace: kaspa
spec:
  routes:
    - match: Host(`tn12-wrpc.kasia.fyi`)
      kind: Rule
      services:
        - name: next-kaspad-external
          kind: Service
          port: 17210
---
apiVersion: v1
kind: Service
metadata:
  name: kaspad-external
  namespace: kaspa
  labels:
    app: next-kaspad
spec:
  selector:
    app: next-kaspad
  ports:
    - name: wrpc-borsh
      port: 17210
      targetPort: 17210
      protocol: TCP
    - name: rpc
      port: 16311
      targetPort: 16311
      protocol: TCP
