apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kaspad
  namespace: kaspa
spec:
  routes:
    - match: Host(`wrpc.kasia.fyi`)
      kind: Rule
      services:
        - name: prod-kaspad-external
          kind: Service
          port: 17110
---
apiVersion: v1
kind: Service
metadata:
  name: kaspad-external
  namespace: kaspa
  labels:
    app: prod-kaspad
spec:
  selector:
    app: prod-kaspad
  ports:
    - name: wrpc-borsh
      port: 17110
      targetPort: 17110
      protocol: TCP
