apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kaspad-grpc
  namespace: kaspa
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`tn12reset-grpc.kasia.fyi`)
      services:
        - name: tn12reset-kaspad-external
          port: 16312
  tls: {}
